/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  collections: {
    users: User;
    categories: Category;
    providers: Provider;
    providersmedia: Providersmedia;
    admins: Admin;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: 'en' | 'sv';
  user: Admin & {
    collection: 'admins';
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  firebaseUserUID: string;
  name?: string | null;
  bio?: string | null;
  locales?:
    | (
        | 'aa'
        | 'ab'
        | 'ae'
        | 'af'
        | 'ak'
        | 'am'
        | 'an'
        | 'ar'
        | 'as'
        | 'av'
        | 'ay'
        | 'az'
        | 'ba'
        | 'be'
        | 'bg'
        | 'bh'
        | 'bi'
        | 'bm'
        | 'bn'
        | 'bo'
        | 'br'
        | 'bs'
        | 'ca'
        | 'ce'
        | 'ch'
        | 'co'
        | 'cr'
        | 'cs'
        | 'cu'
        | 'cv'
        | 'cy'
        | 'da'
        | 'de'
        | 'dv'
        | 'dz'
        | 'ee'
        | 'el'
        | 'en'
        | 'eo'
        | 'es'
        | 'et'
        | 'eu'
        | 'fa'
        | 'ff'
        | 'fi'
        | 'fj'
        | 'fo'
        | 'fr'
        | 'fy'
        | 'ga'
        | 'gd'
        | 'gl'
        | 'gn'
        | 'gu'
        | 'gv'
        | 'ha'
        | 'he'
        | 'hi'
        | 'ho'
        | 'hr'
        | 'ht'
        | 'hu'
        | 'hy'
        | 'hz'
        | 'ia'
        | 'id'
        | 'ie'
        | 'ig'
        | 'ii'
        | 'ik'
        | 'io'
        | 'is'
        | 'it'
        | 'iu'
        | 'ja'
        | 'jv'
        | 'ka'
        | 'kg'
        | 'ki'
        | 'kj'
        | 'kk'
        | 'kl'
        | 'km'
        | 'kn'
        | 'ko'
        | 'kr'
        | 'ks'
        | 'ku'
        | 'kv'
        | 'kw'
        | 'ky'
        | 'la'
        | 'lb'
        | 'lg'
        | 'li'
        | 'ln'
        | 'lo'
        | 'lt'
        | 'lu'
        | 'lv'
        | 'mg'
        | 'mh'
        | 'mi'
        | 'mk'
        | 'ml'
        | 'mn'
        | 'mr'
        | 'ms'
        | 'mt'
        | 'my'
        | 'na'
        | 'nb'
        | 'nd'
        | 'ne'
        | 'ng'
        | 'nl'
        | 'nn'
        | 'no'
        | 'nr'
        | 'nv'
        | 'ny'
        | 'oc'
        | 'oj'
        | 'om'
        | 'or'
        | 'os'
        | 'pa'
        | 'pi'
        | 'pl'
        | 'ps'
        | 'pt'
        | 'qu'
        | 'rm'
        | 'rn'
        | 'ro'
        | 'ru'
        | 'rw'
        | 'sa'
        | 'sc'
        | 'sd'
        | 'se'
        | 'sg'
        | 'si'
        | 'sk'
        | 'sl'
        | 'sm'
        | 'sn'
        | 'so'
        | 'sq'
        | 'sr'
        | 'ss'
        | 'st'
        | 'su'
        | 'sv'
        | 'sw'
        | 'ta'
        | 'te'
        | 'tg'
        | 'th'
        | 'ti'
        | 'tk'
        | 'tl'
        | 'tn'
        | 'to'
        | 'tr'
        | 'ts'
        | 'tt'
        | 'tw'
        | 'ty'
        | 'ug'
        | 'uk'
        | 'ur'
        | 'uz'
        | 've'
        | 'vi'
        | 'vo'
        | 'wa'
        | 'wo'
        | 'xh'
        | 'yi'
        | 'yo'
        | 'za'
        | 'zh'
        | 'zu'
      )[]
    | null;
  devices?:
    | {
        id?: string | null;
        model?: string | null;
        locales?:
          | (
              | 'aa'
              | 'ab'
              | 'ae'
              | 'af'
              | 'ak'
              | 'am'
              | 'an'
              | 'ar'
              | 'as'
              | 'av'
              | 'ay'
              | 'az'
              | 'ba'
              | 'be'
              | 'bg'
              | 'bh'
              | 'bi'
              | 'bm'
              | 'bn'
              | 'bo'
              | 'br'
              | 'bs'
              | 'ca'
              | 'ce'
              | 'ch'
              | 'co'
              | 'cr'
              | 'cs'
              | 'cu'
              | 'cv'
              | 'cy'
              | 'da'
              | 'de'
              | 'dv'
              | 'dz'
              | 'ee'
              | 'el'
              | 'en'
              | 'eo'
              | 'es'
              | 'et'
              | 'eu'
              | 'fa'
              | 'ff'
              | 'fi'
              | 'fj'
              | 'fo'
              | 'fr'
              | 'fy'
              | 'ga'
              | 'gd'
              | 'gl'
              | 'gn'
              | 'gu'
              | 'gv'
              | 'ha'
              | 'he'
              | 'hi'
              | 'ho'
              | 'hr'
              | 'ht'
              | 'hu'
              | 'hy'
              | 'hz'
              | 'ia'
              | 'id'
              | 'ie'
              | 'ig'
              | 'ii'
              | 'ik'
              | 'io'
              | 'is'
              | 'it'
              | 'iu'
              | 'ja'
              | 'jv'
              | 'ka'
              | 'kg'
              | 'ki'
              | 'kj'
              | 'kk'
              | 'kl'
              | 'km'
              | 'kn'
              | 'ko'
              | 'kr'
              | 'ks'
              | 'ku'
              | 'kv'
              | 'kw'
              | 'ky'
              | 'la'
              | 'lb'
              | 'lg'
              | 'li'
              | 'ln'
              | 'lo'
              | 'lt'
              | 'lu'
              | 'lv'
              | 'mg'
              | 'mh'
              | 'mi'
              | 'mk'
              | 'ml'
              | 'mn'
              | 'mr'
              | 'ms'
              | 'mt'
              | 'my'
              | 'na'
              | 'nb'
              | 'nd'
              | 'ne'
              | 'ng'
              | 'nl'
              | 'nn'
              | 'no'
              | 'nr'
              | 'nv'
              | 'ny'
              | 'oc'
              | 'oj'
              | 'om'
              | 'or'
              | 'os'
              | 'pa'
              | 'pi'
              | 'pl'
              | 'ps'
              | 'pt'
              | 'qu'
              | 'rm'
              | 'rn'
              | 'ro'
              | 'ru'
              | 'rw'
              | 'sa'
              | 'sc'
              | 'sd'
              | 'se'
              | 'sg'
              | 'si'
              | 'sk'
              | 'sl'
              | 'sm'
              | 'sn'
              | 'so'
              | 'sq'
              | 'sr'
              | 'ss'
              | 'st'
              | 'su'
              | 'sv'
              | 'sw'
              | 'ta'
              | 'te'
              | 'tg'
              | 'th'
              | 'ti'
              | 'tk'
              | 'tl'
              | 'tn'
              | 'to'
              | 'tr'
              | 'ts'
              | 'tt'
              | 'tw'
              | 'ty'
              | 'ug'
              | 'uk'
              | 'ur'
              | 'uz'
              | 've'
              | 'vi'
              | 'vo'
              | 'wa'
              | 'wo'
              | 'xh'
              | 'yi'
              | 'yo'
              | 'za'
              | 'zh'
              | 'zu'
            )[]
          | null;
        tokens?:
          | {
              token: string;
              type: 'expo' | 'apns' | 'fcm';
              platform?: ('ios' | 'android') | null;
              appVersion?: string | null;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  thumbhash?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    image?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  isFriskvardsEligible?: boolean | null;
  type: 'PHYSICAL_HEALTH' | 'EMOTIONAL_HEALTH';
  providers?: (string | Provider)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: string;
  status?: ('draft' | 'ready-for-review' | 'published') | null;
  user: string | User;
  name: string;
  bio?: string | null;
  categories: (string | Category)[];
  spokenLanguages?:
    | (
        | 'aa'
        | 'ab'
        | 'ae'
        | 'af'
        | 'ak'
        | 'am'
        | 'an'
        | 'ar'
        | 'as'
        | 'av'
        | 'ay'
        | 'az'
        | 'ba'
        | 'be'
        | 'bg'
        | 'bh'
        | 'bi'
        | 'bm'
        | 'bn'
        | 'bo'
        | 'br'
        | 'bs'
        | 'ca'
        | 'ce'
        | 'ch'
        | 'co'
        | 'cr'
        | 'cs'
        | 'cu'
        | 'cv'
        | 'cy'
        | 'da'
        | 'de'
        | 'dv'
        | 'dz'
        | 'ee'
        | 'el'
        | 'en'
        | 'eo'
        | 'es'
        | 'et'
        | 'eu'
        | 'fa'
        | 'ff'
        | 'fi'
        | 'fj'
        | 'fo'
        | 'fr'
        | 'fy'
        | 'ga'
        | 'gd'
        | 'gl'
        | 'gn'
        | 'gu'
        | 'gv'
        | 'ha'
        | 'he'
        | 'hi'
        | 'ho'
        | 'hr'
        | 'ht'
        | 'hu'
        | 'hy'
        | 'hz'
        | 'ia'
        | 'id'
        | 'ie'
        | 'ig'
        | 'ii'
        | 'ik'
        | 'io'
        | 'is'
        | 'it'
        | 'iu'
        | 'ja'
        | 'jv'
        | 'ka'
        | 'kg'
        | 'ki'
        | 'kj'
        | 'kk'
        | 'kl'
        | 'km'
        | 'kn'
        | 'ko'
        | 'kr'
        | 'ks'
        | 'ku'
        | 'kv'
        | 'kw'
        | 'ky'
        | 'la'
        | 'lb'
        | 'lg'
        | 'li'
        | 'ln'
        | 'lo'
        | 'lt'
        | 'lu'
        | 'lv'
        | 'mg'
        | 'mh'
        | 'mi'
        | 'mk'
        | 'ml'
        | 'mn'
        | 'mr'
        | 'ms'
        | 'mt'
        | 'my'
        | 'na'
        | 'nb'
        | 'nd'
        | 'ne'
        | 'ng'
        | 'nl'
        | 'nn'
        | 'no'
        | 'nr'
        | 'nv'
        | 'ny'
        | 'oc'
        | 'oj'
        | 'om'
        | 'or'
        | 'os'
        | 'pa'
        | 'pi'
        | 'pl'
        | 'ps'
        | 'pt'
        | 'qu'
        | 'rm'
        | 'rn'
        | 'ro'
        | 'ru'
        | 'rw'
        | 'sa'
        | 'sc'
        | 'sd'
        | 'se'
        | 'sg'
        | 'si'
        | 'sk'
        | 'sl'
        | 'sm'
        | 'sn'
        | 'so'
        | 'sq'
        | 'sr'
        | 'ss'
        | 'st'
        | 'su'
        | 'sv'
        | 'sw'
        | 'ta'
        | 'te'
        | 'tg'
        | 'th'
        | 'ti'
        | 'tk'
        | 'tl'
        | 'tn'
        | 'to'
        | 'tr'
        | 'ts'
        | 'tt'
        | 'tw'
        | 'ty'
        | 'ug'
        | 'uk'
        | 'ur'
        | 'uz'
        | 've'
        | 'vi'
        | 'vo'
        | 'wa'
        | 'wo'
        | 'xh'
        | 'yi'
        | 'yo'
        | 'za'
        | 'zh'
        | 'zu'
      )[]
    | null;
  merits?:
    | {
        type: 'certification' | 'education' | 'other';
        value: string;
        id?: string | null;
      }[]
    | null;
  media?:
    | {
        media: string | Providersmedia;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providersmedia".
 */
export interface Providersmedia {
  id: string;
  belongsTo: string | Provider;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    image?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}